apiVersion: batch/v1
kind: CronJob
metadata:
  name: minecraft-backup
spec:
  schedule: "0 0 * * *" # Runs every night at midnight
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: s3-backup
              image: amazon/aws-cli:2.15.0
              command:
                - "sh"
                - "-c"
                - |
                  echo "Archiving world data..."
                  tar -czf /tmp/world_backup.tar.gz -C /data .
                  echo "Uploading backup to S3 bucket..."
                  aws s3 cp /tmp/world_backup.tar.gz s3://cs312-minecraft-backups-rhandoua/world_backup.tar.gz --region us-east-1
                  echo "Backup complete!"
              volumeMounts:
                - name: server-data
                  mountPath: /data
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: server-data
              persistentVolumeClaim:
                claimName: minecraft-storage-minecraft-0
